In [1]:
# CSv Analyser
import numpy as np
import pandas as pd

In [2]:
def AutoPrepML(path):
  df = pd.read_csv(path)

  #remove
  pass

In [3]:
df = pd.read_csv("retail_store_sales.csv")
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [4]:
#dataset shape
df.shape

(12575, 11)

In [5]:
#datatypes of columns
df.dtypes

Transaction ID       object
Customer ID          object
Category             object
Item                 object
Price Per Unit      float64
Quantity            float64
Total Spent         float64
Payment Method       object
Location             object
Transaction Date     object
Discount Applied     object
dtype: object

In [6]:
#check null values
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [7]:
#remove constant columns
constant_columns = [col for col in df.columns if df[col].nunique() == 1]
df.drop(columns = constant_columns)
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [8]:
#remove duplicates
df.drop_duplicates(inplace = True)
df.shape

(12575, 11)

In [9]:
#identify columns types
nums_col = []
cat_col = []
for col in df.columns:
  if df[col].dtypes in ['int64', 'float64']:
    nums_col.append(col)
  else:
    cat_col.append(col)

print("nums_col:", nums_col)
print("cat_col:", cat_col)

nums_col: ['Price Per Unit', 'Quantity', 'Total Spent']
cat_col: ['Transaction ID', 'Customer ID', 'Category', 'Item', 'Payment Method', 'Location', 'Transaction Date', 'Discount Applied']

In [10]:
#dealing with missing values
for col in nums_col:
  df[col].fillna(df[col].mean(), inplace = True)

for col in cat_col:
  df[col].fillna(df[col].mode()[0], inplace = True)

df.isnull().sum()

/tmp/ipykernel_3466/3461350167.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace = True)
/tmp/ipykernel_3466/3461350167.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace = True)
/tmp/ipykernel_3466/3461350167.py:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col].fillna(df[col].mode()[0], inplace = True)

Transaction ID      0
Customer ID         0
Category            0
Item                0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Discount Applied    0
dtype: int64

In [11]:
#dealing with outliers
for col in nums_col:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q1 - Q3
  lower = Q1 - 1.5 * IQR
  upper = Q3 + 1.5 * IQR
  df[col] = np.clip(df[col], lower, upper)

df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,248.5,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,True
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [12]:
df.shape

(12575, 11)

In [13]:
#encode categorial data
df = pd.get_dummies(df, columns = cat_col)
df.head()

,Price Per Unit,Quantity,Total Spent,Transaction ID_TXN_1002182,Transaction ID_TXN_1003865,Transaction ID_TXN_1003940,Transaction ID_TXN_1004091,Transaction ID_TXN_1004124,Transaction ID_TXN_1004284,Transaction ID_TXN_1005543,...,Transaction Date_2025-01-11,Transaction Date_2025-01-12,Transaction Date_2025-01-13,Transaction Date_2025-01-14,Transaction Date_2025-01-15,Transaction Date_2025-01-16,Transaction Date_2025-01-17,Transaction Date_2025-01-18,Discount Applied_False,Discount Applied_True
0,18.5,10.0,185.0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,29.0,9.0,248.5,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,21.5,2.0,43.0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,27.5,9.0,247.5,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,12.5,7.0,87.5,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [14]:
#feature scalling
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()
df_scaled = scaler.fit_transform(df)
df = pd.DataFrame(df_scaled, columns = df.columns)
df.head()

,Price Per Unit,Quantity,Total Spent,Transaction ID_TXN_1002182,Transaction ID_TXN_1003865,Transaction ID_TXN_1003940,Transaction ID_TXN_1004091,Transaction ID_TXN_1004124,Transaction ID_TXN_1004284,Transaction ID_TXN_1005543,...,Transaction Date_2025-01-11,Transaction Date_2025-01-12,Transaction Date_2025-01-13,Transaction Date_2025-01-14,Transaction Date_2025-01-15,Transaction Date_2025-01-16,Transaction Date_2025-01-17,Transaction Date_2025-01-18,Discount Applied_False,Discount Applied_True
0,-0.464318,1.600847,0.817889,-0.008918,-0.008918,-0.008918,-0.008918,-0.008918,-0.008918,-0.008918,...,-0.028211,-0.032169,-0.026762,-0.026762,-0.033385,-0.030906,-0.028211,-0.026762,-0.702725,0.702725
1,0.537619,1.242204,1.641495,-0.008918,-0.008918,-0.008918,-0.008918,-0.008918,-0.008918,-0.008918,...,-0.028211,-0.032169,-0.026762,-0.026762,-0.033385,-0.030906,-0.028211,-0.026762,-0.702725,0.702725
2,-0.178050,-1.268298,-1.023877,-0.008918,-0.008918,-0.008918,-0.008918,-0.008918,-0.008918,-0.008918,...,-0.028211,-0.032169,-0.026762,-0.026762,-0.033385,-0.030906,-0.028211,-0.026762,1.423031,-1.423031
3,0.394485,1.242204,1.628525,-0.008918,-0.008918,-0.008918,-0.008918,-0.008918,-0.008918,-0.008918,...,-0.028211,-0.032169,-0.026762,-0.026762,-0.033385,-0.030906,-0.028211,-0.026762,-0.702725,0.702725
4,-1.036853,0.524917,-0.446704,-0.008918,-0.008918,-0.008918,-0.008918,-0.008918,-0.008918,-0.008918,...,-0.028211,-0.032169,-0.026762,-0.026762,-0.033385,-0.030906,-0.028211,-0.026762,1.423031,-1.423031

In [ ]:
#remove multicollinearity
corr_matrix = df.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
to_drop = [column for column in upper.columns if any(upper[column] > 0.9)]
df.drop(columns=to_drop, inplace=True)

In [ ]:
#remove low variance
from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold(threshold=0.05)
df = pd.DataFrame(selector.fit(df))